### ISSUE TITLE
Investment accounts hierarchy example does not render properly.

### ISSUE THREAD

**Issue by lornemelin** [codesmythe/gnucash-docs-rst#10]
At the URL below, the text indicates there is an example of an investment accounts hierarchy.    At the end of the same paragraph is a long string of text which I think is supposed to render as the example hierarchy, but in my browser (latest chrome in windows 10) the text just appears as a long concatenated string and does not render as a hierarchy.

https://gnucash-docs-rst.readthedocs.io/en/latest/guide/C/ch_invest.html#custom-accounts-example

**Comment by codesmythe** [comment]
Hi, this repo is being archive, as it will not be merged upstream.
