### ISSUE TITLE
Incorrect screen snapshot in Investments section

### ISSUE THREAD

**Issue by lornemelin** [codesmythe/gnucash-docs-rst#9]
I'm not certain, (as I'm only myself just learning about tracking investments in GnuCash), but I think the screen snapshot associated with the topic at the following URL, is the wrong screen snapshot.   The image is missing the extra split line with the commission.

 https://gnucash-docs-rst.readthedocs.io/en/latest/guide/C/ch_invest.html#example-buying-shares-with-gross-pricing

**Comment by codesmythe** [comment]
Hi @lornemelin. This repository represents an experiment from three years ago and it not in use. I should archive it. The hoops needed to get this into upstream are higher than I want to deal with. You should direct any changes to https://github.com/Gnucash/gnucash-docs.
